---
- hosts: all
  become: yes
  tasks:
    - name: Install nginx 
      apt: 
         name: nginx 
         state: latest
    - name: Start nginx
      service:
         name: nginx
         state: started
    - name: Install docker 
      apt: 
         name: docker.io
         state: latest
         update_cache: yes
    - name: Start and enable docker 
      service:
         name: docker
         state: started
         enabled: yes  
    - name: Add the user 
      ansible.builtin.user:
         name: zelin
         shell: /bin/bash
         groups: docker
         append: yes
    - name: Set authorized key 
    #please check your type of authorized_key. I use ECDSA  
      ansible.posix.authorized_key:
         user: zelin
         state: present
         key: "{{ lookup('file', '~/.ssh/id_ecdsa.pub') }}"
    - name: Get nginx`s version 
      shell: 
         cmd: nginx -v 
      register: nginx_version
    - name: Debug info
      debug: 
         msg: "{{ nginx_version.stderr }}"